spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.konturlabs.com/auth/realms/dev
          jwk-set-uri: https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs