spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.kontur.io/auth/realms/kontur
          jwk-set-uri: https://keycloak01.kontur.io/auth/realms/kontur/protocol/openid-connect/certs