--- # Time-stamp: <2022-09-21 20:58:50>

name: 10 Manual Deployment

'on':
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Deployment targets (choose one)
        required: true
        default: deploy-dev
        type: choice
        options:
          - deploy-dev
          - deploy-test
          - deploy-prod
      git_ref:
        description: Git ref (optional) # The branch, tag or SHA to checkout
        required: false

jobs:
  helper:
    uses: ./.github/workflows/migration-helper01.yml
  deploy:
    name: '${{ github.event.inputs.deployment_target }}'
    runs-on: ubuntu-latest
    needs: helper
    steps:
      - name: Cloning repository (HEAD)
        uses: actions/checkout@v3
        if: github.event.inputs.git_ref == ''
      - name: 'Cloning repository (${{ github.event.inputs.git_ref }})'
        uses: actions/checkout@v3
        if: github.event.inputs.git_ref != ''
        with:
          ref: '${{ github.event.inputs.git_ref }}'

      - name: Extracting metadata from a cloned repository
        id: get-cloned
        run: |-
          echo "::set-output name=SHA::$(git log -1 --format='%H')"
          echo "::set-output name=REF::$(git symbolic-ref HEAD 2>/dev/null)"

      - name: Download artifact(s)
        id: download-artifact
        uses: konturio/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          commit: '${{steps.get-cloned.outputs.SHA}}'
          name: 'layers-api-${{needs.helper.outputs.CI_COMMIT_REF_SLUG}}'

      - name: Preparing Ansible's environment
        if: >-
          'deploy-dev' == github.event.inputs.deployment_target
          || 'deploy-test' == github.event.inputs.deployment_target
          || 'deploy-prod' == github.event.inputs.deployment_target
        run: |-
          set -e

          wget -q https://kontur-github-runners.s3.eu-central-1.amazonaws.com/public_resources/projects/common/2022091500.tar.xz && tar -C "$HOME" -xf 2022091500.tar.xz && rm 2022091500.tar.xz

          sudo mkdir -p -m 0755 /etc/ansible && sudo wget -q --no-use-server-timestamps -O /etc/ansible/hosts "https://kontur-github-runners.s3.eu-central-1.amazonaws.com/public_resources/ROOT--etc--ansible/hosts"

          mkdir -p -m 0700 ~/.ssh
          cat > ~/.ssh/id_ed25519 <<"EOF"
          ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          EOF
          chmod 0600 ~/.ssh/id_ed25519

          sudo tee /etc/ansible/ansible.cfg <<EOF
          [defaults]
          # (boolean) Set this to "False" if you want to avoid host key checking by the underlying tools Ansible uses to connect to the host
          host_key_checking=False
          EOF

      - name: deploy-dev
        if: "'deploy-dev' == github.event.inputs.deployment_target"
        run: >
          ansible-playbook -vD -e "version=${{needs.helper.outputs.CI_COMMIT_REF_SLUG}}-${{github.run_id}}
          path_to_dist=$(find $GITHUB_WORKSPACE -maxdepth 1 -name layers-api\*.tar.xz -print -quit)"
          --limit=zigzag_user_profile_api ansible/deploy.yml

      - name: deploy-test
        if: "'deploy-test' == github.event.inputs.deployment_target"
        run: >
          ansible-playbook -vD -e "version=${{needs.helper.outputs.CI_COMMIT_REF_SLUG}}-${{github.run_id}}
          path_to_dist=$(find $GITHUB_WORKSPACE -maxdepth 1 -name layers-api\*.tar.xz -print -quit)"
          --limit=sonic_user_profile_api ansible/deploy.yml

      - name: deploy-prod
        if: "'deploy-prod' == github.event.inputs.deployment_target"
        run: >
          ansible-playbook -vD -e "version=${{needs.helper.outputs.CI_COMMIT_REF_SLUG}}-${{github.run_id}}
          path_to_dist=$(find $GITHUB_WORKSPACE -maxdepth 1 -name layers-api\*.tar.xz -print -quit)"
          --limit=lima_user_profile_api ansible/deploy.yml
