--- # Time-stamp: <2022-09-22 09:50:06>

name: 01 Building with Gradle

on:
  push:
    branches:
    - '**'

jobs:
  helper:
    uses: ./.github/workflows/migration-helper01.yml
  gradle:
    runs-on: ubuntu-latest
    needs: helper
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Extracting metadata from a cloned repository
        id: get-cloned
        run: |-
          echo "::set-output name=SHA::$(git log -1 --format='%h')"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.2

      - name: Logging into Kontur Nexus
        env:
          NEXUS_DEPLOYER: ${{ secrets.NEXUS_DEPLOYER }}
          NEXUS_DEPLOYER_PASS: ${{ secrets.NEXUS_DEPLOYER_PASS }}
        run: |-
          set -e
          echo '${{ secrets.NEXUS_DEPLOYER_PASS }}' | docker login nexus.kontur.io:8084 -u '${{ secrets.NEXUS_DEPLOYER }}' --password-stdin
          echo '${{ secrets.NEXUS_DEPLOYER_PASS }}' | docker login nexus.kontur.io:8085 -u '${{ secrets.NEXUS_DEPLOYER }}' --password-stdin

      - name: Checking and building with Gradle
        env:
          IMAGE_TAG: ${{ github.ref_name }}.${{ steps.get-cloned.outputs.SHA }}.${{ github.run_attempt }}
        run: |-
          set -x
          for t in check build jib; do
              sh gradlew --console plain "$t" \
                || { \
                      tar --show-transformed-names --transform="s@^build/reports/tests/test@test_report@" -cvf - build/reports/tests/test/* | xz -1 > test-report-${{needs.helper.outputs.CI_COMMIT_REF_SLUG}}.tar.xz; \
                      sh gradlew --console plain --info "$t"; \
                      exit 1; \
                   }
          done
          set +x
          tar --show-transformed-names --transform="s@^build/libs/@@;s@^build/resources/main/external/@@;" -cvf - build/libs/*.jar build/resources/main/external/* | xz -1 > layers-api-${{needs.helper.outputs.CI_COMMIT_REF_SLUG}}.tar.xz
          # awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' build/jacoco.csv
          echo "<h3>Docker image tag</h3> $IMAGE_TAG <br><br><br>" >> $GITHUB_STEP_SUMMARY

      - name: Uploading build and test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'layers-api-${{needs.helper.outputs.CI_COMMIT_REF_SLUG}}'
          path: '*.tar.xz'

      - name: Publishing JUnit Test result report
        uses: konturio/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
